In [3]:
import numpy as np
dict1 = {}
for i in range(1, 10):
    dict1[i] = sorted(np.arange(10, 20), reverse=True)
    
dict1

{1: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 2: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 3: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 4: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 5: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 6: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 7: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 8: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
 9: [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]}

In [21]:
dict1 = {}
for i in range(1, 10):
    dict1[i] =(np.arange(10, 19).reshape(3, 3))
    
dict1

{1: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 2: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 3: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 4: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 5: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 6: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 7: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 8: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 9: array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])}

In [35]:
# for i in dict1.items():
#       print(i)
for key, value in dict1.items():
    dict1[key][1:2, 0:2] = [40, 50]
dict1


{1: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 2: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 3: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 4: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 5: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 6: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 7: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 8: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]]),
 9: array([[10, 11, 12],
        [40, 50, 15],
        [16, 17, 18]])}

In [16]:

for key,value in dict1.items():
    x = sum(value)/len(value)
    print(key, x)
    print(np.mean(value))
    print(min(value))
    print(max(value))
print(x)

1 14.5
14.5
10
19
2 14.5
14.5
10
19
3 14.5
14.5
10
19
4 14.5
14.5
10
19
5 14.5
14.5
10
19
6 14.5
14.5
10
19
7 14.5
14.5
10
19
8 14.5
14.5
10
19
9 14.5
14.5
10
19
14.5


In [19]:
list1 = []
for key, value in dict1.items():
    for i in value:
        if i>15 :
            list1.append(i)
list1

[19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16,
 19,
 18,
 17,
 16]

In [39]:
x = np.ones((5, 5), dtype=int)
x[1:-1, 1:-1] = 0
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [65]:
a = np.array([10, 20, 60, 70, 80])
b = np.array([10, 20, 30, 40, 50])
# if a in b:
#     print('present')
# else:
#     print('not present)


In [56]:
for i in a:
    for j in b:
        if i==j:
            print(i, j)
    
    
   

10 10
20 20


In [48]:
a in b

True

In [49]:
a>b

array([False, False, False, False, False])

In [57]:
a = np.array([1, 2, 3, 4])
a * 2
a

array([1, 2, 3, 4])

In [60]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [61]:
arr = np.arange(1, 9).reshape(2, 2, 2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [63]:
arr.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])