In [1]:
x = [i if i%2 == 0 else 1 for i in range(1, 15)]
x

[1, 2, 1, 4, 1, 6, 1, 8, 1, 10, 1, 12, 1, 14]

In [2]:
my_dict = {}
for i in range(1, 10):
    my_dict[i] = i*i
my_dict

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [3]:
x = {i: i*i for i in range(1, 10)}
x

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [4]:
import numpy as np
x = np.zeros((3,3), dtype=int)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
arr = np.arange(11, 0, -1)
arr

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [6]:
if 20 in arr:
    print('exist')
else:
    print('not exist')

not exist


In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])
arr1 + arr2

array([ 5,  7,  9, 11, 13])

In [8]:
arr1 * arr2

array([ 4, 10, 18, 28, 40])

In [9]:
arr1 < arr2

array([ True,  True,  True,  True,  True])

In [10]:
arr1[arr1 % 2 == 0]

array([2, 4])

In [11]:
np.greater(arr1, arr2)

array([False, False, False, False, False])

In [12]:
np.less(arr1, arr2)

array([ True,  True,  True,  True,  True])

In [13]:
np.array_equal(arr1, arr2)

False

In [14]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(1, 20, 40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [16]:
1 - 1.47368421

-0.47368421000000005

In [17]:
1.47368421 - 1.94736842

-0.47368421000000005

In [18]:
np.empty([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
x = np.arange(1, 16, 1).reshape(5, 3).transpose()
x

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])

In [21]:
x[2][2] 

9

In [22]:
a = None
for i in x:
    for y in i:
        if y>i :
            a 
        print(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
a

In [24]:
a = 0
for i in x:
    print(x[i])
    for y in range(len(x[i])):
        print(a>x[i][y])
#         if a>x[i][y]:
#             a = x[i][y]
#             print(a)      
                
        


IndexError: index 4 is out of bounds for axis 0 with size 3

In [25]:
x = np.arange(2, 20)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
x.reshape(6, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [27]:
#row exist in array
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
if 30 in arr:
     print('exist')
else:
    print('not exist')

not exist


In [29]:
print([ 1,  2,  3,  4,  5] in arr.tolist())

True


In [30]:
print([ 1,  -5,  3,  10,  5] in arr.tolist())

False


In [31]:

list1 = [12.23, 13.32, 100, 36.32]
x = np.array(list1)
x

array([ 12.23,  13.32, 100.  ,  36.32])

In [33]:
a = np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [34]:
#create a null vector of size 10 and update sixth value to 11.
x = np.zeros(10, dtype=int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
x[6] = 11
x

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0])

In [36]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [37]:
np.arange(38, 11, -1)

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [38]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [39]:
x = np.ones((5,5), dtype=int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
x[1:-1, 1:-1] = 0
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [41]:
x = [10, 20, 30]
y = np.append(x, [[40,50, 60], [70,80,90]])
y

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
import numpy as np

In [43]:
arr = np.array([1,2, 3])
arr

array([1, 2, 3])

In [44]:
for x in arr:
    print(x)

1
2
3


In [45]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
for x in arr1:
    print(x)
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [52]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr.ndim

3

In [62]:
for x in arr:
#     print(x)
    for y in x:
#         print(y)
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [64]:
arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
a = 0
for i in arr:
#     print(i)
    for x in i:
        if x%2 == 0:
#             print(x)
            if a<x:
                print(a)

0
0
0
0


In [88]:
#joining numpy arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.concatenate((arr1, arr2))
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((arr1, arr2), axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [91]:
#stacking
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.stack((arr1, arr2), axis=1)
arr3

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [92]:
#stacking along horizontal rows
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.hstack((arr1, arr2))
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
#stacking aling columns
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.vstack((arr1, arr2))
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
#sorting arrays
arr = np.array([3, 0, 5, 1, 8])
arr

array([3, 0, 5, 1, 8])

In [95]:
new_arr = np.sort(arr)
new_arr

array([0, 1, 3, 5, 8])

In [96]:
#reshape convert 1D TO 2D OR 2D
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
x= arr.reshape(4, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [99]:
y = arr.reshape(2, 5, 2)
y

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [100]:
y.ndim

3

In [101]:
arr1 = np.arange(1, 13)
arr1 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
arr1.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [106]:
arr1.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])