In [1]:
list1 = []
for i in range(1, 10):
    list1.append(i)
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
my_list = [1, 2, 3, 4, 1, 5, 4, 6]
# new_list = []
set(my_list)

{1, 2, 3, 4, 5, 6}

In [3]:
new_list = []
for i in range(len(my_list)):
    if my_list[i] not in new_list:
        if my_list[i] % 2 == 0:
            new_list.append(my_list[i])
new_list

[2, 4, 6]

In [4]:
list1 = []
list2 = []
for i in range(1, 10):
    list1.append(i)
print(list1)
for i in range(11, 20):
    list2.append(i)
print(list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19]


In [5]:
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])
print(list3)
    

[12, 14, 16, 18, 20, 22, 24, 26, 28]


In [6]:
list3.sort(reverse=True)
list3

[28, 26, 24, 22, 20, 18, 16, 14, 12]

In [7]:
import random

x = random.randint(1, 50)
x

23

In [8]:
y = random.sample(range(1, 100), 10)
y

[1, 86, 11, 20, 33, 45, 57, 63, 5, 48]

In [9]:
my_list = []
for i in range(1, 10):
    my_list.append(random.randint(1, 50))
my_list

[19, 31, 43, 31, 45, 22, 2, 46, 9]

In [13]:
# my_list1 = []
# my_list1.append(random.sample(1, 100), 10)
# my_list1

In [14]:
my_list1 = [1, 42, 45, 48, 2, 5, 8]
my_list1.sort()
my_list1

[1, 2, 5, 8, 42, 45, 48]

In [15]:
my_list1.insert(1,20)
my_list1

[1, 20, 2, 5, 8, 42, 45, 48]

In [16]:
my_list1.pop()

48

In [17]:
my_list1.pop(2)
my_list1

[1, 20, 5, 8, 42, 45]

In [18]:
new_list = [10, 20, 30, 40, 50, 60]
# new_list.pop()
# new_list.remove(40)
new_list.pop(1)
new_list

[10, 30, 40, 50, 60]

In [19]:
list1 = ['cat', 'dog', 'rabit']
for letter in list1:
    for ch in letter:
        print(ch)

c
a
t
d
o
g
r
a
b
i
t


In [20]:
set1 = {'apple', 'banana', 'cherry'}
set1

{'apple', 'banana', 'cherry'}

In [21]:
set1.add('kiwi')
set1

{'apple', 'banana', 'cherry', 'kiwi'}

In [22]:
set1 = {1, 2, 3, 4, 5}
set2 = {2, 4, 5, 6, 7, 8}

In [23]:
set1.difference(set2)

{1, 3}

In [24]:
set2.difference(set1)

{6, 7, 8}

In [25]:
set1.difference_update(set2)
set1

{1, 3}

In [26]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7, 8}

In [27]:
set3 = {'a', 'b', 'c', 'd'}
set4 = {'b', 'c', 'e', 'f'}
x = set3.intersection(set4)
x

{'b', 'c'}

In [28]:
my_dict = {'name': 'john', 'age': 10, 'sub': 'maths'}
my_dict['age']

10

In [ ]:
my_dict['color'] = 'blue'
my_dict

In [29]:
for key in my_dict.items():
    print(key)

('name', 'john')
('age', 10)
('sub', 'maths')


In [30]:
new_dict = {}
for i in range(1, 10):
    new_dict[i]= i*i
new_dict

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [31]:
dict1 = {'a': 4, 'c': 10, 'b': 1, 'e': 3}
# sorted(dict1.items())
sorted(dict1.values())

[1, 3, 4, 10]

In [32]:
dict2 = {}
for i in range(1, 10):
    dict2[i] = random.randint(10, 20)

# sorted(dict2.values())
dict2

{1: 15, 2: 12, 3: 19, 4: 17, 5: 19, 6: 18, 7: 16, 8: 17, 9: 12}

In [33]:
dict3 = {}
for i in range(1, 10):
    dict3[i] = random.sample(range(1, 20), 10)
dict3

{1: [6, 16, 14, 10, 17, 18, 9, 2, 7, 12],
 2: [17, 16, 14, 10, 2, 1, 18, 9, 6, 11],
 3: [16, 10, 13, 1, 4, 8, 11, 5, 6, 9],
 4: [15, 14, 9, 19, 1, 4, 5, 7, 18, 17],
 5: [2, 5, 15, 7, 11, 12, 4, 19, 1, 10],
 6: [7, 5, 4, 17, 16, 14, 1, 13, 10, 9],
 7: [1, 13, 11, 7, 4, 19, 3, 14, 8, 12],
 8: [16, 8, 19, 11, 3, 15, 17, 12, 4, 2],
 9: [8, 6, 17, 18, 2, 15, 4, 7, 16, 1]}

In [34]:
people = {'p1': {'name': 'john', 'age': 25, 'proffe': 'artist'},
            'p2': {'name': 'john', 'age': 30, 'proffe': 'singer'}}
people['p3'] = {}
people['p3']['name'] = 'cris'
people['p3']['age'] = 35
people['p3']['proffe'] = 'engineer'
people['p3']['gender'] = 'male'
people['p3']

{'name': 'cris', 'age': 35, 'proffe': 'engineer', 'gender': 'male'}

In [35]:
people

{'p1': {'name': 'john', 'age': 25, 'proffe': 'artist'},
 'p2': {'name': 'john', 'age': 30, 'proffe': 'singer'},
 'p3': {'name': 'cris', 'age': 35, 'proffe': 'engineer', 'gender': 'male'}}

In [36]:
people['p3']['proffe']

'engineer'

In [37]:
people['p2']['gender'] = 'male'
people

{'p1': {'name': 'john', 'age': 25, 'proffe': 'artist'},
 'p2': {'name': 'john', 'age': 30, 'proffe': 'singer', 'gender': 'male'},
 'p3': {'name': 'cris', 'age': 35, 'proffe': 'engineer', 'gender': 'male'}}

In [38]:
del people['p3']['gender']

In [39]:
people

{'p1': {'name': 'john', 'age': 25, 'proffe': 'artist'},
 'p2': {'name': 'john', 'age': 30, 'proffe': 'singer', 'gender': 'male'},
 'p3': {'name': 'cris', 'age': 35, 'proffe': 'engineer'}}

In [40]:
people['p1']['sub'] = ['maths', 'social',  'english']
people['p1']

{'name': 'john',
 'age': 25,
 'proffe': 'artist',
 'sub': ['maths', 'social', 'english']}

In [41]:
people['p1']['sub'][1]

'social'

In [42]:
fruits = ['mango', 'apple', 'banana', 'cherry']
new_list = [x for x in fruits if 'a' in x]
new_list

['mango', 'apple', 'banana']

In [43]:
x = [i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
y = [i for i in range(50) if i%2 == 0 and i%5 == 0]
y

[0, 10, 20, 30, 40]

In [45]:
y = ['even' if i%2 == 0 else 'odd'  for i in range(1, 10)]
y

['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

In [46]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [47]:
arr.ndim

1

In [48]:
arr.reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [49]:
np.arange(10, 35, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])

In [50]:
np.empty([2,3], dtype=int)

array([[6029370, 7536725, 7471205],
       [6029427, 6619212, 7274606]])

In [51]:
a = ([1,2,3], [4,5,6])
np.empty_like([a])

array([[[6357102, 7274595, 6553710],
        [3342433, 4980828, 6422633]]])

In [52]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [53]:
y = np.arange(1, 10)
y = y.reshape(3, 3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.zeros_like(y)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [55]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [56]:
x = np.arange(6)
x =x.reshape(2, 3)
x


array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [58]:
np.full((2,3), 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [59]:
np.full((2,3), [1,2,3])

array([[1, 2, 3],
       [1, 2, 3]])

In [60]:
np.full((2,3), [[1,2,3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
x = np.arange(6)
np.full_like(x, 2)

array([2, 2, 2, 2, 2, 2])

In [62]:
x = np.array([1, 2, 3])
y = x
y

array([1, 2, 3])

In [63]:
x[0] = 10
x

array([10,  2,  3])

In [64]:
y

array([10,  2,  3])

In [65]:
z = np.copy(x)
z

array([10,  2,  3])

In [66]:
x[1] = 20
x

array([10, 20,  3])

In [67]:
z

array([10,  2,  3])

In [68]:
np.arange(1, 20, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [69]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [70]:
x = 40
y = 100
z = [(i * x)/y for i in np.arange(1, 10, 1)]
z

[0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6]

In [71]:
np.linspace(1, 50, 20, dtype=int)

array([ 1,  3,  6,  8, 11, 13, 16, 19, 21, 24, 26, 29, 31, 34, 37, 39, 42,
       44, 47, 50])

In [72]:
x = np.zeros((3, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
x[1: , 1:] = 9
x

array([[0., 0., 0.],
       [0., 9., 9.],
       [0., 9., 9.]])

In [74]:
np.random.rand(2, 2)

array([[0.83425779, 0.71795078],
       [0.77378184, 0.06778998]])

In [75]:
np.random.randint(2, size=10)

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1])

In [76]:
np.random.randint(7, size=(2,3))

array([[5, 4, 5],
       [6, 6, 6]])

In [77]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.arange(0, 20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
import pandas as pd
df = pd.DataFrame(np.arange(0, 20).reshape(4,5), index=['0', '1', '2', '3'], columns=['col1', 'col2', 'col3', 'col4', 'col5'])

In [80]:
df

col1  col2  col3  col4  col5
0     0     1     2     3     4
1     5     6     7     8     9
2    10    11    12    13    14
3    15    16    17    18    19

In [81]:
#access elements
df.loc['0']

col1    0
col2    1
col3    2
col4    3
col5    4
Name: 0, dtype: int32

In [82]:
type(df.loc['0'])

pandas.core.series.Series

In [83]:
df.iloc[1:3, 0:2]

col1  col2
1     5     6
2    10    11

In [84]:
type(df.iloc[1:3, 0:2])

pandas.core.frame.DataFrame

In [85]:
df.iloc[0:2, 0]

0    0
1    5
Name: col1, dtype: int32

In [86]:
type(df.iloc[0:2, 0])

pandas.core.series.Series

In [87]:
#convert dat'aframe into arrays
df.iloc[:, 1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [88]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64

In [89]:
df['col1'].value_counts()

0     1
5     1
10    1
15    1
Name: col1, dtype: int64

In [90]:
df['col1'].unique()

array([ 0,  5, 10, 15])

In [91]:
df['col1'].nunique()

4

In [92]:
df = pd.read_csv("Desktop/mercedesbenz.csv")

In [93]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [94]:
df.shape

(4209, 378)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [96]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [ ]:
import pandas as pd